[project]
name = "mspeeps"
version = "0.1.3"
description = "MSP File Scraping"
authors = ["gkreder <gk@reder.io>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = ">=3.12.0,<3.13"
pandas = ">=2.2.3,<3"
pytest = ">=8.3.5,<9"

[pypi-dependencies]
pymzml = ">=2.5.11, <3"
rdkit = ">=2024.9.6, <2025"
openpyxl = ">=3.1.5, <4"
fragfit = ">=0.1.2, <0.2"
